services:
  post-tracker-db-postgresql:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=post-tracker
      - POSTGRES_USER=developer
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
